version: '3.8'

services:
  laravel-backend:
    build: 
      context: ./laravel-backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./laravel-backend:/var/www/html
    environment:
      - DB_HOST=mysql
      - DB_DATABASE=laravel-backend
      - DB_USERNAME=root
      - DB_PASSWORD=
      - APP_ENV=local
      - APP_DEBUG=true
    depends_on:
      - mysql
    working_dir: /var/www/html
    command: >
      sh -c "
        cp .env.docker .env &&
        php artisan key:generate &&
        php artisan migrate --force &&
        php artisan db:seed --force &&
        php artisan serve --host=0.0.0.0 --port=8000
      "

  nextjs-frontend:
    build:
      context: ./nextjs-frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./nextjs-frontend:/app
      - /app/node_modules
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:8000/api
    depends_on:
      - laravel-backend
    working_dir: /app

  mysql:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: laravel-backend
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password

volumes:
  mysql_data: